export default [
  {
    id: "A1",
    name: "Focaccia",
    ingredients: "Pão com azeite de olívia italiano",
    price: 6,
    photoName: "pizzas/focaccia.jpg",
    soldOut: false,
  },
  {
    id: "B2",
    name: "Pizza Margherita",
    ingredients: "Tomate, mussarela e manjericão",
    price: 10,
    photoName: "pizzas/margherita.jpg",
    soldOut: false,
  },
  {
    id: "C3",
    name: "Pizza Espinafre",
    ingredients: "Tomate, mussarela, espinafre, e queijo de ricotta",
    price: 12,
    photoName: "pizzas/spinaci.jpg",
    soldOut: false,
  },
  {
    id: "D4",
    name: "Pizza Funghi",
    ingredients: "Tomate, mussarela, cogumêlos, e cebola",
    price: 12,
    photoName: "pizzas/funghi.jpg",
    soldOut: false,
  },
  {
    id: "E5",
    name: "Pizza Salamino",
    ingredients: "Tomate, mussarela, e pepperoni",
    price: 15,
    photoName: "pizzas/salamino.jpg",
    soldOut: true,
  },
  {
    id: "F6",
    name: "Pizza Prosciutto",
    ingredients: "Tomate, mussarela, presunto, rúcula, e queijo burrata",
    price: 18,
    photoName: "pizzas/prosciutto.jpg",
    soldOut: false,
  },
];
